---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The container creation to use the RPC-O container artifact repository
lxc_image_cache_server: "{{ rpco_mirror_base_url | netloc_no_port }}"

# Set the lxc_hosts base image prep to use the RPC-O base image artifact
lxc_cache_default_variant: "default-{{ rpc_release }}"

# The default variant to be used for all containers if there
# is no specific group override.
lxc_container_variant: "{{ lxc_cache_default_variant }}"

# TODO(odyssey4me)
# The 'no-validate' option should be removed once this work is done:
#   https://github.com/rcbops/u-suk-dev/issues/1296
lxc_cache_download_template_extra_options: "--no-validate"

# TODO(odyssey4me)
# The 'no-validate' option should be removed once this work is done:
#   https://github.com/rcbops/u-suk-dev/issues/1296
lxc_container_download_template_extra_options: "--no-validate"

# As we pre-build our container images, they have no ssh keys in them.
# The ssh keys are required in order for delegation from a container to
# another container to work. eg: os-keystone-install delegates the
# rabbitmq and mariadb tasks from the keystone container to the
# respective rabbit/mariadb container.
# TODO(odyssey4me)
# In Pike onwards this will no longer be required, so remove it then.
lxc_container_commands: |
  key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  mkdir -p /root/.ssh
  chmod 700 /root/.ssh
  if [[ ! "$(grep -q "$key" /root/.ssh/authorized_keys)" ]]; then
    echo "$key" | tee -a /root/.ssh/authorized_keys
  fi
  chmod 700 /root/.ssh/authorized_keys
