---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Pre install config for ironic
  hosts: ironic_all
  tasks:
    - name: Define networks for ironic to use
      config_template:
        src: "/etc/openstack_deploy/openstack_user_config.yml"
        dest: "/etc/openstack_deploy/openstack_user_config.yml"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ cidr_networks_ironic }}"
        config_type: "yaml"

    - name: Add IPs to used_ips list
      config_template:
        src: "/etc/openstack_deploy/openstack_user_config.yml"
        dest: "/etc/openstack_deploy/openstack_user_config.yml"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ used_ips }}"
        config_type: "yaml"

    - name: Setup global overrides
      config_template:
        src: "/etc/openstack_deploy/openstack_user_config.yml"
        dest: "/etc/openstack_deploy/openstack_user_config.yml"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ ironic_networks }}"
        config_type: "yaml"

    - name: Define group hosts
      config_template:
        src: "/etc/openstack_deploy/openstack_user_config.yml"
        dest: "/etc/openstack_deploy/openstack_user_config.yml"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ group_hosts_ironic }}"
        config_type: "yaml"

    - name: Setup endpoints for swift/ironic health checks
      config_template:
       src: "/etc/openstack_deploy/user_osa_variables_overrides.yml"
       dest: "/etc/openstack_deploy/user_osa_variables_overrides.yml"
       owner: "root"
       group: "root"
       mode: "0644"
       config_overrides: "{{ ironic_endpoint_config }}"
       config_type: "yaml"

    - name: Configure neutron DHCP to be non-authorative
      config_template:
        src: "/etc/openstack_deploy/user_osa_variables_overrides.yml"
        dest: "/etc/openstack_deploy/user_osa_variables_overrides.yml"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ ironic_neutron_dhcp_config }}"
        config_type: "yaml"

    - name: Setup neutron network
      os_network:
        shared: yes
        provider_physical_network: "tftp"
        provider_network_type: "flat tftp"


    - name: Setup neutron subnet
      os_subnet:
        name: "ironic-ipmi"
        allocation_pool_start: "<NON_ALLOCATED_TFTP_RANGE_START>"
        allocation_pool_end: "<NON_ALLOCATED_TFTP_RANGE_END>"
        dns_nameservers: "4.4.4.4 tftp <TFTP_NETWORK>/<TFTP_NETMASK>"

  vars:
    cidr_networks_ironic:
      cidr_networks:
           tftp: "{{ tftp_network }}/{{ tftp_netmask }}"
           ironic-ipmi: "{{ ironic-ipmi_network }}/{{ ironic-ipmi_netmask }}"
    ironic_networks:
      - network:
          container_bridge: "br-ironic-ipmi"
          container_type: "veth"
          container_interface: "eth_ipmi"
          ip_from_q: "ironic-ipmi"
          type: "raw"
          group_binds:
          - ironic-infra_hosts
      - network:
          container_bridge: "br-tftp"
          container_type: "veth"
          container_interface: "eth_tftp"
          ip_from_q: "ironic-ipmi"
          type: "flat"
          net_name: "tftp"
          ip_from_q: "tftp"
          group_binds:
          - neutron_linuxbridge_agent
          - ironic_all
    group_hosts_ironic:
      ironic-compute_hosts:
        infra01:
          ip: "{{ infra01_mgmt_ip }}"
        infra02:
          ip: "{{ infra02_mgmt_ip }}"
        infra03:
          ip: "{{ infra03_mgmt_ip }}"
      ironic-infra_hosts:
        infra01:
          ip: "{{ infra01_mgmt_ip }}"
        infra02:
          ip: "{{ infra02_mgmt_ip }}"
        infra03:
          ip: "{{ infra03_mgmt_ip }}"
    ironic_endpoint_config:
      extra_lb_vip_addresses:
        - <IP address>
      ironic_openstack_api_url: "<IP address>:{{ ironic_service_port }}"
      ironic_swift_endpoint: "<IP address>:8080"
    ironic_neutron_dhcp_config:
      neutron_dhcp_config:
        dhcp-option-force: "26,1500"
        dhcp-ignore: "tag:!known"
        log-facility: "/var/log/neutron/dnsmasq.log"
    used_ips:
